// <auto-generated />
namespace CupcakeYPasteles.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cascasf34rescv : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cascasf34rescv));
        
        string IMigrationMetadata.Id
        {
            get { return "201711201854505_cascasf34rescv"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
